version: '3.7'

services: 
  nuxtjs:
    image: pine:step3
    build: .
    ports: 
      - "3000:3000"
      - "3001:3001"
    environment: 
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_ACCESS_TIME=${JWT_ACCESS_TIME}
      - JWT_REFRESH_TIME=${JWT_REFRESH_TIME}
    tty: true
    volumes: 
      - ./app:/app
      - /app/node_modules
    depends_on: 
      - mysql
  
  mysql:
    image: mysql:8.0.22
    ports: 
      - "3307:3306"
    cap_add:
      - SYS_NICE
    volumes: 
      - pine:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes: 
  pine: